// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: service/upload/upload.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UplaodService service

func NewUplaodServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UplaodService service

type UplaodService interface {
	UploadEntry(ctx context.Context, in *ReqEntry, opts ...client.CallOption) (*RespReqEntry, error)
}

type uplaodService struct {
	c    client.Client
	name string
}

func NewUplaodService(name string, c client.Client) UplaodService {
	return &uplaodService{
		c:    c,
		name: name,
	}
}

func (c *uplaodService) UploadEntry(ctx context.Context, in *ReqEntry, opts ...client.CallOption) (*RespReqEntry, error) {
	req := c.c.NewRequest(c.name, "UplaodService.UploadEntry", in)
	out := new(RespReqEntry)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UplaodService service

type UplaodServiceHandler interface {
	UploadEntry(context.Context, *ReqEntry, *RespReqEntry) error
}

func RegisterUplaodServiceHandler(s server.Server, hdlr UplaodServiceHandler, opts ...server.HandlerOption) error {
	type uplaodService interface {
		UploadEntry(ctx context.Context, in *ReqEntry, out *RespReqEntry) error
	}
	type UplaodService struct {
		uplaodService
	}
	h := &uplaodServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UplaodService{h}, opts...))
}

type uplaodServiceHandler struct {
	UplaodServiceHandler
}

func (h *uplaodServiceHandler) UploadEntry(ctx context.Context, in *ReqEntry, out *RespReqEntry) error {
	return h.UplaodServiceHandler.UploadEntry(ctx, in, out)
}
